language: python
cache: pip
dist: xenial
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  allow_failures:
    - python: 3.8-dev
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
      sudo: true
before_install:
  - sudo apt-get install -y tree
# command to install dependencies
install: "make"
# command to run tests
script:
  - make test
after_success:
  - tree .
  - coveralls
  - make lint
  - make check_format
