language: python
cache: pip
dist: trusty
python:
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  allow_failures:
    - python: 3.8-dev
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      dist: xenial
      sudo: true
# command to install dependencies
install: "make"
# command to run tests
script:
  - make test
after_success:
  - coveralls
  - make lint
  - make check_format
